### ISSUE TITLE
Will it support transform BGR to RGB for 3-channel images?

### ISSUE THREAD

**Issue by zhiqwang** [google/mediapy#1]
Hi mediapy team!

Thanks for sharing this awesome tool. It seems that the color map only support `grey` to `RGB` currently. Because opencv uses `BGR` by default and it's also widely used. I want to know if there are some plans to support this channel mode, and if this mode is already supported, could you give me some hints where this interface is?

**Comment by hhoppe** [comment]
Could you please give an example?
The function `to_rgb()` returns a numpy array with RGB channels, so `to_rgb()[..., ::-1]` would give BGR channels.

Given a BGR image `array`, one can operate on it as an RGB image using `array[..., ::-1]`.  Hope that helps.

**Comment by zhiqwang** [comment]
Hi @hhoppe

Thanks for you quickly reply, it sounds reasonable to me! Use `array[..., ::-1]` can solve this problem.

My origional is thought a parameter to address this situation automatically like following

```python
media.show_image(array, border=True, cmap='rgb', height=400)
```
