### ISSUE TITLE
video show no content

### ISSUE THREAD

**Issue by UTINK** [google/mediapy#27]
simple code, but output video shows no content.

![image](https://user-images.githubusercontent.com/56284816/218418578-fab687f1-fb04-4bb8-8d3e-4324c02df7a5.png)

checked that variant video has value
and have installed ffmpeg and set it in the system path.

**Comment by hhoppe** [comment]
Unfortunately I cannot reproduce the problem.

Does it work when ran in Colab, e.g., https://colab.research.google.com/github/google/mediapy/blob/main/mediapy_examples.ipynb ?

Please try `!pip show mediapy` to see the version number, and similarly `!ffmpeg -version`.

Also, try generating the video at size `(200, 200)` and pressing the play/pause button in the video window.

**Comment by UTINK** [comment]
> Unfortunately I cannot reproduce the problem.
> 
> Does it work when ran in Colab, e.g., https://colab.research.google.com/github/google/mediapy/blob/main/mediapy_examples.ipynb ?
> 
> Please try `!pip show mediapy` to see the version number, and similarly `!ffmpeg -version`.
> 
> Also, try generating the video at size `(200, 200)` and pressing the play/pause button in the video window.

_________________________________________________________________

It works well in Colab and Chrome.

But the problem still exists in PyCharm.

**Comment by hhoppe** [comment]
I have not used PyCharm.  Access to Jupyter notebook requires PyCharm Pro?
It could be that the display of videos as implemented by `mediapy` does not function under PyCharm.

You could also try:
```python
media.show_video(video, fps=10, codec='gif')
```
This uses an `<img>` rather than `<video>` HTML element.

**Comment by UTINK** [comment]
‘gif’ works. 

btw, why can't  **mediapy** display video when using the plugin Jupyter notebook in PyCharm Pro?

**Comment by hhoppe** [comment]
Probably PyCharm does not support the display of HTML <video> tags with embedded data.
