### ISSUE TITLE
Unable to parse video framerate in line

### ISSUE THREAD

**Issue by JunyaoHu** [google/mediapy#32]
![city-cond-0](https://github.com/google/mediapy/assets/67564714/6c574b0b-edec-48ce-a283-c7195aae9d20)

I want to use mediapy.read_video to read it but there is something wrong because this gif only has 2 frames and has not fps metadata. how to read it by using mediapy?

**Comment by hhoppe** [comment]
This was fixed in https://github.com/google/mediapy/pull/34
