### ISSUE TITLE
Side by side image comparison slider

### ISSUE THREAD

**Issue by abhijitkundu** [google/mediapy#33]
This library is awesome. Will like to make a feature request to add some functions that makes it easy to do side by side image comparison with a slider. There are some html/css elements that does this like https://www.npmjs.com/package/img-comparison-slider https://juxtapose.knightlab.com/ which may be useful. A easy way to do slider based image comparison in colabs/notebooks apart from side by side viewing via mediapy will be very convenient.

**Comment by hhoppe** [comment]
Thanks for the great suggestion.  We added this feature in PR #35 .
