### ISSUE TITLE
Large videos

### ISSUE THREAD

**Issue by YoussefBarada96** [google/mediapy#5]
Hii, I would like to ask how can I open large videos (.avi format) using mediapy. 
The problem is when I try to open large video the system freezes for a while than it is closed with no errors.
Hence I would like to know if mediapy doesn't support large files. 
Thanks in advance

**Comment by hhoppe** [comment]
Are you using `read_video()` as in https://google.github.io/mediapy/#mediapy.read_video to read the entire video into an array?
Have you tried reading using `VideoReader` as in https://google.github.io/mediapy/#mediapy.VideoReader to instead read frame-by-frame?

**Comment by YoussefBarada96** [comment]
I need to access the frames by index that's why I am using read_video() not VideoReader.

**Comment by hhoppe** [comment]
What is the access pattern?

**Comment by PWhiddy** [comment]
@YoussefBarada96 maybe you are running out of memory? A numpy array storing even just a 1 min video as 32-bit floats is 1920*1080*60*60*4 bytes, or almost 30GB.

**Comment by hhoppe** [comment]
Closing this issue; the video was likely too large to load all-at-once into memory.
