### ISSUE TITLE
question about write_video

### ISSUE THREAD

**Issue by Tsingularity** [google/mediapy#6]
Hi, thanks for open-sourcing the great library!

I am just curious in your demo notebook, when saving the video:
```
# Write a video to a file:
media.write_video('/tmp/video1.mp4', video1, fps=10, qp=10)
```
what does 'qp' here mean? I searched online but didn't find anything.

Thanks in advance!

**Comment by hhoppe** [comment]
It stands for ["quantization parameter"](https://www.google.com/search?q=%22quantization+parameter%22) and is the low-level quality knob in modern video codecs.  (Lower values give higher quality.)

**Comment by Tsingularity** [comment]
thanks!
